/**
 * Builds a single CSS bundle: pruned design tokens (only used variables + dependencies)
 * plus all global navigation CSS. Writes src/generated/gnav-styles.css.
 * Run from libs/global-navigation (project root).
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const TOKEN_DIR = path.join(ROOT, 'consonant/dist/packages/tokens/css/dev');
const TOKEN_FILES = [
  'tokens.primitives.css',
  'tokens.semantic.css',
  'tokens.semantic.light.css',
];

const GNAV_CSS_FILES = [
  'src/styles/styles.css',
  'src/Components/Brand/brand.css',
  'src/Components/MegaMenu/mega-menu.css',
  'src/Components/GnavCards/gnav-cards.css',
  'src/Components/PromoCard/promo-card.css',
  'src/Components/LinksCard/links-card.css',
  'src/Components/ProductList/productlist.css',
  'src/Components/Panels/panels.css',
  'src/Components/FeaturedCard/featured-card.css',
];

const OUT_FILE = path.join(ROOT, 'src/generated/gnav-styles.css');

/** Extract all var(--name) and var(--name, ...) from CSS text. Returns Set of '--name'. */
function collectVarRefs(css) {
  const set = new Set();
  const re = /var\s*\(\s*(--[a-zA-Z0-9_-]+)/g;
  let m;
  while ((m = re.exec(css)) !== null) set.add(m[1]);
  return set;
}

/** Parse a token CSS file into { selector, declarations: [{ name, value }] }. */
function parseTokenFile(content) {
  const result = [];
  const blockRe = /(:\s*root(?:\[[^\]]+\])?)\s*\{([^}]+)\}/g;
  let m;
  while ((m = blockRe.exec(content)) !== null) {
    const selector = m[1].trim();
    const body = m[2];
    const decls = [];
    const declRe = /(--[a-zA-Z0-9_-]+)\s*:\s*([^;]+);/g;
    let d;
    while ((d = declRe.exec(body)) !== null) decls.push({ name: d[1], value: d[2].trim() });
    result.push({ selector, declarations: decls });
  }
  return result;
}

/** Build map of variable name -> list of var names referenced in its value. */
function buildDependencyGraph(parsedTokenBlocks) {
  const graph = new Map();
  for (const block of parsedTokenBlocks) {
    for (const { name, value } of block.declarations) {
      const deps = collectVarRefs(value);
      if (deps.size) graph.set(name, [...deps]);
    }
  }
  return graph;
}

/** Transitive closure: start with used set, add any variable referenced in a kept variable's value. */
function resolveDependencies(used, graph) {
  const keep = new Set(used);
  let added = true;
  while (added) {
    added = false;
    for (const name of keep) {
      const deps = graph.get(name);
      if (deps) {
        for (const d of deps) {
          if (!keep.has(d)) {
            keep.add(d);
            added = true;
          }
        }
      }
    }
  }
  return keep;
}

async function main() {
  const tokenContent = [];
  for (const file of TOKEN_FILES) {
    const p = path.join(TOKEN_DIR, file);
    const content = await fs.readFile(p, 'utf8');
    tokenContent.push(content);
  }

  let gnavCss = '';
  for (const rel of GNAV_CSS_FILES) {
    const p = path.join(ROOT, rel);
    gnavCss += await fs.readFile(p, 'utf8');
    gnavCss += '\n';
  }

  const combinedCss = tokenContent.join('\n') + '\n' + gnavCss;
  const used = collectVarRefs(combinedCss);

  const parsedBlocks = [];
  for (const content of tokenContent) parsedBlocks.push(...parseTokenFile(content));

  const graph = buildDependencyGraph(parsedBlocks);
  const keep = resolveDependencies(used, graph);

  const outLines = [
    '/**',
    ' * Generated by scripts/build-css.js - do not edit.',
    ' * Pruned design tokens (used by gnav) + global navigation CSS.',
    ' */',
    '',
  ];

  for (const block of parsedBlocks) {
    const kept = block.declarations.filter((d) => keep.has(d.name));
    if (kept.length === 0) continue;
    outLines.push(`${block.selector} {`);
    for (const { name, value } of kept) {
      outLines.push(`  ${name}: ${value};`);
    }
    outLines.push('}');
    outLines.push('');
  }

  outLines.push('/* ========== Gnav component styles ========== */');
  outLines.push('');
  outLines.push(gnavCss.trimEnd());

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, outLines.join('\n') + '\n', 'utf8');
  console.log('CSS bundle written to', path.relative(ROOT, OUT_FILE));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
